### ISSUE TITLE
Test error on test_mathtext for Python 3.6

### ISSUE THREAD

**Issue by matthew-brett** [MacPython/matplotlib-wheels#3]
I just got the Python 3.6 build and tests working with the fix from #2, but now I get this error:

```
======================================================================

ERROR: matplotlib.tests.test_mathtext.test_mathtext_cm_53.test

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/Users/travis/build/MacPython/matplotlib-wheels/venv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/Users/travis/build/MacPython/matplotlib-wheels/venv/lib/python3.6/site-packages/matplotlib/testing/decorators.py", line 53, in failer

    result = f(*args, **kwargs)

  File "/Users/travis/build/MacPython/matplotlib-wheels/venv/lib/python3.6/site-packages/matplotlib/testing/decorators.py", line 207, in do_test

    figure.savefig(actual_fname, **self._savefig_kwarg)

  File "/Users/travis/build/MacPython/matplotlib-wheels/venv/lib/python3.6/site-packages/matplotlib/figure.py", line 1563, in savefig

[snip]

 File "/Users/travis/build/MacPython/matplotlib-wheels/venv/lib/python3.6/site-packages/pyparsing.py", line 1510, in _parseCache

    value = cache.get(lookup)

  File "/Users/travis/build/MacPython/matplotlib-wheels/venv/lib/python3.6/site-packages/pyparsing.py", line 1459, in get

    return cache.get(key, not_in_cache)

RecursionError: maximum recursion depth exceeded
```

https://s3.amazonaws.com/archive.travis-ci.org/jobs/187592465/log.txt

Any insight into what's going on there?

**Comment by matthew-brett** [comment]
Same error testing v2.x:

https://api.travis-ci.org/jobs/187655630/log.txt?deansi=true

**Comment by tacaswell** [comment]
Odd.  We have been running 3.6 tests against the pre-releases on travis for a while.  Can you reproduce this one locally?

**Comment by matthew-brett** [comment]
Sigh.  Yes, but only when running the full test suite, not the individual tests.  Have you got a Mac to test on?

**Comment by tacaswell** [comment]
I do not have easy access to a mac
